// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3x7rqNGKIHNL7BYqe3qxKks2MdnfkNUE',
    appId: '1:196164512969:web:cd7310223af56bbfdf7118',
    messagingSenderId: '196164512969',
    projectId: 'date-convertor-events',
    authDomain: 'date-convertor-events.firebaseapp.com',
    storageBucket: 'date-convertor-events.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFWwmWQ0jXJl0bPYhnOttnYeI5-TpEI-s',
    appId: '1:196164512969:android:edac56e4e0337f02df7118',
    messagingSenderId: '196164512969',
    projectId: 'date-convertor-events',
    storageBucket: 'date-convertor-events.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIpuaxk6QPsYFg5FXh-RufIxNLtlx50N8',
    appId: '1:196164512969:ios:ce0cf3bd406747dadf7118',
    messagingSenderId: '196164512969',
    projectId: 'date-convertor-events',
    storageBucket: 'date-convertor-events.appspot.com',
    iosClientId: '196164512969-qbehgg74it012l0i5mqem89n7ecrg648.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIpuaxk6QPsYFg5FXh-RufIxNLtlx50N8',
    appId: '1:196164512969:ios:ce0cf3bd406747dadf7118',
    messagingSenderId: '196164512969',
    projectId: 'date-convertor-events',
    storageBucket: 'date-convertor-events.appspot.com',
    iosClientId: '196164512969-qbehgg74it012l0i5mqem89n7ecrg648.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
